POST http://localhost:3000/users/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMDg1NzQ0MywiZXhwIjoxNzMwODYxMDQzfQ.A2fWPudF7-UaaYmzUNh9sA1WPr8nBUIKfE2GnECvxEA

{
  "userId": 1,
  "name": "Priscila",
  "email": "teste2@exemplo.com",
  "password": "novasenha123"
}
