GET http://localhost:3000/emotions/by-date?year=2024&month=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMDQ5NDIxNCwiZXhwIjoxNzMwNDk3ODE0fQ.VPWG5ZlnxX8XVTSkhJwj6kAlsN33fbu8rVZn8Mrqkxo