GET http://localhost:3000/emotions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMDQ3NjU2OCwiZXhwIjoxNzMwNDgwMTY4fQ.3r10NycKhQXdnNDLQE9Ow0rOsT_EJSbM1_UsydXJdzQ
