GET http://localhost:3000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMDkxMzAwMiwiZXhwIjoxNzMwOTE2NjAyfQ.l7sJ7Ac-c19tLvwzoqQTidKcI2CO1Jffwvcd0V4U0RM
